version: '3'
services:
  seq:
    # 自訂義名稱
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "80:80"
      - "5341:5341"
    volumes:
      - ./data:/data
    environment:
      - ACCEPT_EULA=Y
      # - SEQ_API_CANONICALURI=https://seq.example.com/
    restart: always