version: '3'
services:
  nginx:
    container_name: my-nginx
    image: nginx:latest
    ports:
      # local:container
      - "80:80"
      - "443:443"
    volumes:
      # local:container
      - ./conf:/etc/nginx
      - ./ssl:/etc/ssl/nginx
      - ./log:/var/log/nginx
    restart: always
